export const authConstants = { 
   LOGIN_REQUEST : ' LOGIN_REQUEST',
   LOGIN_FAILURE : ' LOGIN_FAILURE',
   LOGIN_SUCCESS : ' LOGIN_SUCCESS',
   LOGOUT_REQUEST : ' LOGOUT_REQUEST',
   LOGOUT_SUCCESS  : ' LOGOUT_SUCCESS',
   LOGOUT_FAILURE  : ' LOGOUT_FAILURE',
}

export const registerConstants = { 
   USER_REGISTER_REQUEST : ' USER_REGISTER_REQUEST',
   USER_REGISTER_FAILURE : '  USER_REGISTER_FAILURE',
   USER_REGISTER_SUCCESS : ' USER_REGISTER_SUCCESS',
   
}



export const categoryConstants = { 
   GET_ALL_CATEGORIES_REQUEST : ' GET_ALL_CATEGORIES_REQUEST',
   GET_ALL_CATEGORIES_FAILURE : ' GET_ALL_CATEGORIES_FAILURE',
   GET_ALL_CATEGORIES_SUCCESS : ' GET_ALL_CATEGORIES_SUCCESS',
   ADD_NEW_CATEGORY_REQUEST : 'ADD_NEW_CATEGORY_REQUEST',
   ADD_NEW_CATEGORY_FAILURE : 'ADD_NEW_CATEGORY_FAILURE',
   ADD_NEW_CATEGORY_SUCCESS : ' ADD_NEW_CATEGORY_SUCCESS',
   UPDATE_CATEGORIES_REQUEST : 'UPDATE_CATEGORIES_REQUEST',
   UPDATE_CATEGORIES_FAILURE : 'UPDATE_CATEGORIES_FAILURE',
   UPDATE_CATEGORIES_SUCCESS : 'UPDATE_CATEGORIES_SUCCESS',
   DELETE_CATEGORIES_REQUEST : 'DELETE_CATEGORIES_REQUEST',
   DELETE_CATEGORIES_FAILURE : 'DELETE_CATEGORIES_FAILURE',
   DELETE_CATEGORIES_SUCCESS : 'DELETE_CATEGORIES_SUCCESS',
}



export const brandConstants = { 
   GET_ALL_BRANDS_REQUEST : ' GET_ALL_BRANDS_REQUEST',
   GET_ALL_BRANDS_FAILURE : ' GET_ALL_BRANDS_FAILURE',
   GET_ALL_BRANDS_SUCCESS : ' GET_ALL_BRANDS_SUCCESS',

   ADD_NEW_BRAND_REQUEST : 'ADD_NEW_BRAND_REQUEST',
   ADD_NEW_BRAND_FAILURE : 'ADD_NEW_BRAND_FAILURE',
   ADD_NEW_BRAND_SUCCESS : ' ADD_NEW_BRAND_SUCCESS',

   UPDATE_BRAND_REQUEST : 'UPDATE_BRAND_REQUEST',
   UPDATE_BRAND_FAILURE : 'UPDATE_BRAND_FAILURE',
   UPDATE_BRAND_SUCCESS : 'UPDATE_BRAND_SUCCESS',

   DELETE_BRAND_REQUEST : 'DELETE_BRAND_REQUEST',
   DELETE_BRAND_FAILURE : 'DELETE_BRAND_FAILURE',
   DELETE_BRAND_SUCCESS : 'DELETE_BRAND_SUCCESS',
}


export const productConstants = { 
   GET_ALL_PRODUCTS_REQUEST : ' GET_ALL_PRODUCTS_REQUEST',
   GET_ALL_PRODUCTS_FAILURE : ' GET_ALL_PRODUCTS_FAILURE',
   GET_ALL_PRODUCTS_SUCCESS : ' GET_ALL_PRODUCTS_SUCCESS',

   
  DELETE_PRODUCT_BY_ID_REQUEST: "DELETE_PRODUCT_BY_ID_REQUEST",
  DELETE_PRODUCT_BY_ID_SUCCESS: "DELETE_PRODUCT_BY_ID_SUCCESS",
  DELETE_PRODUCT_BY_ID_FAILURE: "DELETE_PRODUCT_BY_ID_FAILURE",

  ADD_PRODUCT_REQUEST: "ADD_PRODUCT_REQUEST",
  ADD_PRODUCT_SUCCESS: "ADD_PRODUCT_SUCCESS",
  ADD_PRODUCT_FAILURE: "ADD_PRODUCT_FAILURE",

  
  UPDATE_PRODUCT_REQUEST: "UPDATE_PRODUCT_REQUEST",
  UPDATE_PRODUCT_SUCCESS: "UPDATE_PRODUCT_SUCCESS",
  UPDATE_PRODUCT_FAILURE: "UPDATE_PRODUCT_FAILURE",
}



export const initDataConstants = { 
   GET_ALL_INITDATA_REQUEST : ' GET_ALL_INITDATA_REQUEST',
   GET_ALL_INITDATA_FAILURE : ' GET_ALL_INITDATA_FAILURE',
   GET_ALL_INITDATA_SUCCESS : ' GET_ALL_INITDATA_SUCCESS',
}



export const pageConstants = { 
   CREATE_PAGE_REQUEST : ' CREATE_PAGE_REQUEST ',
   CREATE_PAGE_FAILURE : ' CREATE_PAGE_FAILURE',
   CREATE_PAGE_SUCCESS : ' CREATE_PAGE_SUCCESS',
}



export const orderConstants = {
   GET_CUSTOMER_ORDER_REQUEST: "GET_CUSTOMER_ORDER_REQUEST",
   GET_CUSTOMER_ORDER_SUCCESS: "GET_CUSTOMER_ORDER_SUCCESS",
   GET_CUSTOMER_ORDER_FAILURE: "GET_CUSTOMER_ORDER_FAILURE",
 
   UPDATE_CUSTOMER_ORDER_REQUEST: "UPDATE_CUSTOMER_ORDER_REQUEST",
   UPDATE_CUSTOMER_ORDER_SUCCESS: "UPDATE_CUSTOMER_ORDER_SUCCESS",
   UPDATE_CUSTOMER_ORDER_FAILURE: "UPDATE_CUSTOMER_ORDER_FAILURE",
 };




 

export const settingConstants = {
   GET_SETTING_PAGE_REQUEST: "GET_SETTING_PAGE_REQUEST",
   GET_SETTING_PAGE_SUCCESS: "GET_SETTING_PAGE_SUCCESS",
   GET_SETTING_PAGE_FAILURE: "GET_SETTING_PAGE_FAILURE",
 
   CREATE_SETTING_PAGE_REQUEST : '  CREATE_SETTING_PAGE_REQUEST',
   CREATE_SETTING_PAGE_SUCCESS : '  CREATE_SETTING_PAGE_SUCCESS',
   CREATE_SETTING_PAGE_FAILURE : '  CREATE_SETTING_PAGE_FAILURE',
  
 };